- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - rhel

- hosts: jboss-hosts
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - jboss-eap

- hosts: mod-cluster-hosts
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - mod-cluster