# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - update-so

- hosts: jboss-hosts
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - install-openjdk