- name: Validate User
  shell: id "{{ APACHE_USER }}" | grep -c "{{ APACHE_USER }}"
  ignore_errors: true
  register: validate_user

- name: Creating user
  command: useradd "{{ APACHE_USER }}" 
  when: validate_user.stdout == '0'

- name: User Already Exists in the System
  shell: id "{{ APACHE_USER }}"
  register: user_info
  when: validate_user.stdout == '1'