- name: attaching subscriptions
  command: subscription-manager attach --auto

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  
- name: Rebooting servers
  tags: reboot
  become: yes
  become_user: root
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Wait for the reboot to complete if there was a change
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 60

- name: Check the Uptime of the servers
  shell: "uptime"
  register: uptime

- debug: var=uptime
