- name: Copy local files to a remote host, transferring files via SSH
  ansible.builtin.copy:
    src: roles/jboss-patch-apply/pakages/patches/
    dest: /home/{{JBOSS_USER}}/
    owner: "{{ JBOSS_USER }}"
    mode: '0644'
    
- name: Get patches
  ansible.builtin.shell: ls -lrth /home/{{JBOSS_USER}}/ | awk '{print $9}'
  register: patches

- name: Get hostname
  ansible.builtin.shell: hostname
  register: hostname

- name: Apply currente patches
  ansible.builtin.shell: "{{ JBOSS_HOME }}/bin/./jboss-cli.sh -c --command='patch apply /home/{{JBOSS_USER}}/{{ item }} --host={{hostname.stdout.split('.')[0]}}' && {{ JBOSS_HOME }}/bin/./jboss-cli.sh -c --command='/host={{hostname.stdout.split('.')[0]}}:shutdown(restart)' && sleep 15"
  ignore_errors: true
  with_items: "{{ patches.stdout_lines }}"
  register: patch_apply

- name: Deleting patches files
  ansible.builtin.shell: rm -rf /home/{{JBOSS_USER}}/{{ item }}
  with_items: "{{ patches.stdout_lines }}"